### ISSUE TITLE
Enspara problems with Ragged Array flattening 

### ISSUE THREAD

**Issue by matthew-cruz** [bowman-lab/enspara#217] opened 2022-12-12 16:30 UTC
Cross posting just in case its at the wrong repo https://github.com/bowman-lab/MSM-docking/issues/17#issue-1492276426

**Comment by justinrporter** [comment] 2022-12-14 21:32
Link seems to be dead?

**Comment by lgsmith** [comment] 2022-12-14 21:35
Matt closed the issue because the error was caused by the ragged array
being empty for reasons unrelated to enspara.

**Comment by Justin-J-Miller** [comment] 2023-05-25 19:08
Closing as this is resolved.

**Closed by Justin-J-Miller** 2023-05-25 19:08 UTC
